### ISSUE TITLE
run_evaluation.sh Issue

### ISSUE THREAD

**Issue by varunjammula** [carla-simulator/leaderboard#92]
Hi,

I am using conda environment with Python 3.8, ubuntu 20.
CARLA is 0.9.11 which I built locally.

I am encountering the following issue: 

Traceback (most recent call last):
  File "/mnt/e3641809-fbba-49ea-86ed-f89021679b99/home/varun/carla/PythonAPI/leaderboard/leaderboard/leaderboard_evaluator.py", line 343, in _load_and_run_scenario
    self.manager.run_scenario()
  File "/mnt/e3641809-fbba-49ea-86ed-f89021679b99/home/varun/carla/PythonAPI/leaderboard/leaderboard/scenarios/scenario_manager.py", line 140, in run_scenario
    self._tick_scenario(timestamp)
  File "/mnt/e3641809-fbba-49ea-86ed-f89021679b99/home/varun/carla/PythonAPI/leaderboard/leaderboard/scenarios/scenario_manager.py", line 154, in _tick_scenario
    self._watchdog.pause()
AttributeError: 'Watchdog' object has no attribute 'pause'

![image](https://user-images.githubusercontent.com/3236409/117365882-d0f3a580-ae74-11eb-87c0-c83bb10fbbe8.png)

**Comment by varunjammula** [comment]
This is happening because the scenario_runner API, changed. I am trying to update the code to make it work with 0.9.11 scenario_runner API.

**Comment by varunjammula** [comment]
Fixed here: https://github.com/varunjammula/leaderboard
